{% set name = "nexusformat" %}
{% set version = "2.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 14de2c1f90c7ba2ad05c57ae3f4a5e14af0043fc7dbadbdd49d1fec9b0e9a76b

build:
  number: 0
  entry_points:
    - nexusformat=nexusformat.scripts.nexusformat:main
    - nxconsolidate=nexusformat.scripts.nxconsolidate:main
    - nxdir=nexusformat.scripts.nxdir:main
    - nxduplicate=nexusformat.scripts.nxduplicate:main
    - nxstack=nexusformat.scripts.nxstack:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools >=64
    - setuptools_scm >=8
  run:
    - python >={{ python_min }}
    - numpy
    - h5py
    - scipy
    - hdf5plugin
    - colored
    - pygments
    - packaging
    - python-dateutil

test:
  requires:
    - python {{ python_min }}
  imports:
    - nexusformat
    - nexusformat.nexus
    - nexusformat.scripts
  commands:
    - nexusformat --help
    - nxconsolidate --help
    - nxdir --help
    - nxduplicate --help
    - nxstack --help

about:
  home: https://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'nexusformat: Python API to access NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexusformat

extra:
  recipe-maintainers:
    - rayosborn
