{% set name = "nexusformat" %}
{% set version = "0.7.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 785b5431276f8747f4243164ada2befe2fceb0a63aceaad2485e50eed5997cb1

build:
  number: 0
  entry_points:
    - nxstack=nexusformat.scripts.nxstack:main
    - nxduplicate=nexusformat.scripts.nxduplicate:main
    - nexusformat=nexusformat.scripts.nexusformat:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - pip
    - python >=3.6
    - setuptools
    - numpy
  run:
    - h5py
    - ipython
    - numpy >=1.16.0
    - python >=3.6

test:
  imports:
    - nexusformat
    - nexusformat.nexus
    - nexusformat.scripts
  commands:
    - nxstack --help
    - nxduplicate --help
    - nexusformat --help

about:
  home: https://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'nexusformat: Python API to access NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexusformat

extra:
  recipe-maintainers:
    - tschoonj
    - rayosborn
