{% set name = "nexusformat" %}
{% set version = "0.7.8" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: dc0fc0ba502fd506b7361c8691e2a8e5388f0df633dbdb9c05adccb9a6044be2

build:
  number: 0
  entry_points:
    - nexusformat=nexusformat.scripts.nexusformat:main
    - nxconsolidate=nexusformat.scripts.nxconsolidate:main
    - nxdir=nexusformat.scripts.nxdir:main
    - nxduplicate=nexusformat.scripts.nxduplicate:main
    - nxstack=nexusformat.scripts.nxstack:main
  noarch: python
  script: '{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vv '

requirements:
  host:
    - python >=3.6
    - pip
    - setuptools >=45
    - setuptools_scm >=6.2
  run:
    - python >=3.6
    - numpy
    - h5py >=2.9
    - scipy

test:
  imports:
    - nexusformat
    - nexusformat.nexus
    - nexusformat.scripts
  commands:
    - nexusformat --help
    - nxconsolidate --help
    - nxdir --help
    - nxduplicate --help
    - nxstack --help

about:
  home: https://nexpy.github.io/nexpy/
  license: BSD-3-Clause
  license_family: BSD
  license_file: COPYING
  summary: 'nexusformat: Python API to access NeXus data'
  doc_url: https://nexpy.github.io/nexpy/
  dev_url: https://github.com/nexpy/nexusformat

extra:
  recipe-maintainers:
    - tschoonj
    - rayosborn
