travis:
  secure:
    BINSTAR_TOKEN: uay3E+eeV15eq7ltclubQLEvBwH1G2gWv4axzgIsjEntNVXPkUYyVBl14YXqUcol9y27tp3a9QtkHhtuaKZUz71GhDbe1K3wKItnXh0y8mwLMtaOjI1hG+CGESW+1HWx8QDL4UoJGZ4DcvrW0dM46r7O2WxdKULv9j/MAcCwC74cY6/wnsaCjHalUD2cJREk2jkxrqou9+whRwojuSXAgoc3QiFn09Z4kwIaKV+KhOdZLPF5+pteBGg8iPhC+hZhK6MrFsbd0V4KS4kGBBnAf5thQZ1A5ayeYaEmg5Xt8OwqigaGySpvyJBfegke3yKIEAfYQSvzQC4uC7tQzjzIulGcYQ9DSX9sqYpDAsnciDp5RsF5FqYBeUCvxru1vToMjzrKJ0nOnLsxOLX1fSm/pUHt1zKoqyDei/rJkZAp+WSfwnPaMzwT1DjQfBsld4y+LWeoeDdUGxQcefpqe4sbXIMQuKrvBzgLsfVhAfZbSFnfeFO+J+E649Ojdr5N1XrGX6w/8ekuUWyDsFJ4nfpVllgoaeQvPVvRj+A6nBup+LntBnq+5NR/sUjpbhiM7kO2ldakTj4E2jgPDRTuzKH0NxrKqSG8k/9sGxrSPdUAtwi1E79gn8QVXPiPz2h6WYLHaUnmn2Ek9Mcs4l1yAf30Pk/mtY0f4b7CUWkn5uEmgao=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
